louvre_booking_home:
    path: /home
    defaults: { _controller: LouvreBookingBundle:Booking:index }

louvre_booking_booking:
    path: /booking
    defaults: { _controller: LouvreBookingBundle:Booking:booking }    

louvre_booking_ticket:
    path: /ticket
    defaults: { _controller: LouvreBookingBundle:Booking:ticket }

louvre_booking_review:
    path: /recap
    defaults: { _controller: LouvreBookingBundle:Booking:recap }

louvre_booking_confirm:
    path: /confirm
    defaults: { _controller: LouvreBookingBundle:Booking:confirm }