louvre_booking_home:
    path: /
    defaults: { _controller: LouvreBookingBundle:Booking:index }

louvre_booking_ticket:
    path: /ticket
    defaults: { _controller: LouvreBookingBundle:Booking:ticket }

louvre_booking_review:
    path: /recap
    defaults: { _controller: LouvreBookingBundle:Booking:recap }