services:
    louvre_booking.priceChecker:
        class: Louvre\BookingBundle\BookingManager\LouvrePriceChecker

    louvre_booking.dateChecker:
        class: Louvre\BookingBundle\BookingManager\LouvreDateChecker

    louvre_booking.typeChecker:
        class: Louvre\BookingBundle\BookingManager\LouvreTypeChecker