<?php

namespace Louvre\BookingBundle\Repository;


use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
 * BookingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookingRepository extends \Doctrine\ORM\EntityRepository
{
	public function ticketsSold(\DateTime $date)
	{
		$qb = $this->createQueryBuilder('b');
		$qb
			->where('b.date = :date')
			->setParameter('date', $date)
		;
		$bookings = $qb->getQuery()->getResult();
		
		$totalTickets = 0;
		foreach ($bookings as $booking)
		{
			$nbTickets = $booking->getNbTickets();
			$totalTickets += $nbTickets;
		}

		return $totalTickets;
	}
}
